### ISSUE TITLE
Mange user media API request

### ISSUE THREAD

**Issue by vcbose** [vcbose/celebrity_be#2]
Option for to mange user medias based on plan
Media types: Images and embedded videos from YouTub or Vimeo

- First check user plan feature count for uploading media
- If count greater that 0 then he can upload media as per his plan count

**Comment by Vivek-Prabhakar** [comment]
Media upload API completed

Request body format : 
{
	"user_id" : " user id ",
	"user_video" :['video urls in array format'],
	"user_image" : ['base64 image data in array format']	
}

**Comment by Vivek-Prabhakar** [comment]
Media upload completed need to test the API
